apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
---
apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    app: flask
spec:
  containers:
  - name: flask
    image: drpeace/duo-deploy-flask:latest # Dockerhub
    ports:
    - containerPort: 5500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
metadata:
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
      image: drpeace/duo-deploy-flask:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5500
      env:
      - name: Chris
        value: Magos